---
- name: Make sure nodejs_version is set correctly.
  assert:
    that: nodejs.nodejs_version in [ "0.10", "0.12" ]

- name: Install nodejs repository
  sudo: yes
  shell: curl -sL https://deb.nodesource.com/setup_"{{ nodejs.nodejs_version }}" | sudo -E bash -
  when: nodejs.install == "1"
  with_items: nodejs.nodejs_version

- name: Install nodejs
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - nodejs
  when: nodejs.install == "1"

- name: Symlink nodejs to node
  sudo: yes
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
  when: nodejs.install == "1"

- name: Ensure Node.js is installed.
  apt: "name=nodejs state=present update_cache=yes"
  when: nodejs.install == "1"

- name: Install forever (to run Node.js apps).
  npm: name=forever global=yes state=latest
  when: nodejs.nodejs_forever and nodejs.install == "1"

- name: Install additional defined npm global packages.
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('') }}"
    global: yes
    state: latest
  with_items: nodejs.nodejs_npm_global_packages
  when: nodejs.install == "1"
