- name: Check if Php is installed
  command: dpkg-query -l php5
  register: is_installed
  failed_when: is_installed.rc > 1
  changed_when: no

- name: Install Composer
  sudo: yes
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer
  when: is_installed.rc == 0 and composer.install == '1'

- name: Composer home folder
  file: path=/home/vagrant/.composer state=directory owner=vagrant group=vagrant
  when: is_installed.rc == 0 and composer.install == '1' and composer.auth

#- name: Composer auth file
#  file: path=/home/vagrant/.composer/auth.json state=touch
#
#- name: Composer auth template
#  template: src=auth.tpl dest=/home/vagrant/.composer/auth.json group=vagrant owner=vagrant
#  when: is_installed.rc == 0 and composer.install == '1' and composer.auth