---
- name: Install add-apt-repostory
  sudo: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  sudo: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java License
  sudo: yes
  debconf: name='oracle-java"{{ java.java_version }}"-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java"{{ java.java_version }}"-installer
    - ca-certificates
    - oracle-java"{{ java.java_version }}"-set-default
