---
- name: Add MariaDB-Repository
  sudo: yes
  apt_repository: repo='deb http://mariadb.mirror.digitalpacific.com.au/repo/10.1/ubuntu {{ ansible_distribution_release }} main' state=present
  when: mariadb.install == '1'

- name: Add Key for MariaDB Repository
  sudo: yes
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db
  when: mariadb.install == '1'
  register: maria_rep

- name: Update apt
  sudo: yes
  apt: update_cache=yes
  when: mariadb.install == '1' and maria_rep.changed != false

- name: mariadb | Install MariaDB Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - mariadb-server
    - python-mysqldb
  when: mariadb.install == '1'

- name: mariadb | Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mariadb.root_password }} login_user=root login_password={{ mariadb.root_password }}
  with_items:
    - "{{ vm.hostname | lower }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: mariadb.install == '1'

- name: mariadb | Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mariadb.root_password }}
  with_items:
    - localhost
    - "{{ vm.hostname | lower }}"
  when: mariadb.install == '1'

- name: mariadb | Create databases
  mysql_db: name={{ mariadb.database }} state=present login_user=root login_password={{ mariadb.root_password }}
  when: mariadb.install == '1'

- name: mariadb | Import dump
  mysql_db: name={{ mariadb.database }} state=import login_user=root login_password={{ mariadb.root_password }} target=/vagrant/{{ mariadb.dump }}
  when: mariadb.dump and mariadb.install == '1'

- name: mariadb | Create users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    login_user: root
    login_password: "{{ mariadb.root_password }}"
    state: present
  with_items: mariadb.users

- name: Copy my.cnf global MySQL configuration.
  template:
    src: my.cnf.tpl
    dest: "/etc/mysql/my.cnf"
    owner: root
    group: root
    mode: 0644
  notify: restart mariadb

#Install Adminer Requires Apache
- name: Check if Apache is installed
  command: dpkg-query -l apache2
  register: is_installed
  failed_when: is_installed.rc > 1
  changed_when: no

- name: Install Adminer
  sudo: yes
  file: path=/usr/share/adminer state=directory mode=0755
  when: mariadb.install == '1' and mariadb.adminer == '1' and is_installed.rc == 0

- name: Download Adminer
  sudo: yes
  get_url: url=http://www.adminer.org/latest.php dest=/usr/share/adminer/latest.php
  when: mariadb.install == '1' and mariadb.adminer == '1' and is_installed.rc == 0

- name: Link Adminer
  sudo: yes
  file: src=/usr/share/adminer/latest.php dest=/usr/share/adminer/adminer.php owner=vagrant group=vagrant state=link
  when: mariadb.install == '1' and mariadb.adminer == '1' and is_installed.rc == 0

- name: Create Apache Conf for Adminer
  sudo: yes
  lineinfile: dest=/etc/apache2/conf-available/adminer.conf line="Alias /adminer.php /usr/share/adminer/adminer.php" create=yes state=present
  when: mariadb.install == '1' and mariadb.adminer == '1' and is_installed.rc == 0
  register: adminer_conf

- name: Install Apache Conf for Adminer
  sudo: yes
  shell: a2enconf adminer.conf
  notify: restart apache maria
  when: mariadb.install == '1' and mariadb.adminer == '1' and is_installed.rc == 0 and adminer_conf.changed == true
